# Refer https://github.com/maciakl/Sample-Jekyll-Site/blob/master/_config.yml
name: tnzkorg.github.io 
description: some writings  
author: tnzk.org, LLC
author_email: contact@tnzk.org 
category_dir: /
baseurl: 
url: http://tnzkorg.github.io/
markdown: rdiscount
permalink: pretty
paginate: 3
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
